export const TOGGLE_SNACKBAR_ACTIVE = "TOGGLE_SNACKBAR_ACTIVE"
export const TOGGLE_SNACKBAR_INACTIVE = "TOGGLE_SNACKBAR_INACTIVE"

export const TOGGLE_LOADING = "TOGGLE_LOADING"

export const SET_USER = "SET_USER"
export const UNSET_USER = "UNSET_USER"